#!/system/bin/sh
#
# Anarkia1976
# Enable Frandom
#

chmod 644 /dev/frandom
mv /dev/random /dev/random.ori
mv /dev/urandom /dev/urandom.ori
ln /dev/frandom /dev/random
chmod 644 /dev/random
ln /dev/frandom /dev/urandom
chmod 644 /dev/urandom
