#!/system/bin/sh
#
# Anarkia1976
# Cleaning Folletto Style
#

LOG_FILE=/data/ak/cleaning.log

#if [ -e $LOG_FILE ]; then
#	rm $LOG_FILE;
#fi;

echo""; echo "Folletto Cleaning Start $( date +"%m-%d-%Y %H:%M:%S" )" | tee -a $LOG_FILE

rm -rf /data/lost+found/* 2> /dev/null;
rm -rf /system/lost+found/* 2> /dev/null;
rm -rf /preload/lost+found/* 2> /dev/null;
rm -rf /cache/lost+found/* 2> /dev/null;
rm -rf /data/tombstones/* 2> /dev/null;
rm -rf /data/anr/* 2> /dev/null;
rm -rf /cache/*.apkbusybox;
rm -rf /cache/*.tmpbusybox;
rm -rf /data/dalvik-cache/*.apkbusybox;
rm -rf /data/dalvik-cache/*.tmp;

echo "Folletto Cleaning finished at $( date +"%m-%d-%Y %H:%M:%S" )" | tee -a $LOG_FILE
