#!/system/bin/sh
#
# Anarkia1976
# Wipe Battery Stat if 100%
#

log=/data/ak/battery.log
bb="/sbin/bb/busybox"

#if [ -e $LOG_FILE ]; then
#	rm $LOG_FILE;
#fi;

$bb echo "";
exec >>$log 2>&1
$bb date >>$log

$bb echo "-------------------------------------------------------------";
echo "Starting Battery Check $( date +"%m-%d-%Y %H:%M:%S" )";

LEVEL=`cat /sys/class/power_supply/battery/capacity`;
CURR_ADC=`cat /sys/class/power_supply/battery/voltage_now`;
BATTFULL=`cat /sys/class/power_supply/battery/status`;

$bb echo "*** LEVEL: $LEVEL - CUR: $CURR_ADC - STATUS: $BATTFULL ***";

if [ "$LEVEL" == "100" ] && [ "$BATTFULL" == "Full" ]; then
 $bb rm -f /data/system/batterystats.bin;
 $bb echo "Battery-calibration done ...";
fi;

$bb echo "Battery Check finished at $( date +"%m-%d-%Y %H:%M:%S" )";
$bb echo "-------------------------------------------------------------";

exit
