#!/system/bin/sh
#
# Anarkia1976
# Much faster zipalign.
#

bb="/sbin/bb/busybox"
LOG_FILE=/data/ak/zipalign.log
ZIPALIGNDB=/data/ak/zipalign.db
ZIP_APKS=/system/bin/zipalign

if [ -e $LOG_FILE ]; then
	rm $LOG_FILE;
fi;

if [ ! -f $ZIPALIGNDB ]; then
	touch $ZIPALIGNDB;
fi;

$bb echo "";
exec >>$LOG_FILE 2>&1
$bb date >>$LOG_FILE

$bb echo "-------------------------------------------------------------";
$bb echo "Starting Automatic ZipAlign $( date +"%m-%d-%Y %H:%M:%S" )";

for DIR in /system/app /data/app ; do
  cd $DIR
  for APK in *.apk ; do
    if [ $APK -ot $ZIPALIGNDB ] && [ $(grep "$DIR/$APK" $ZIPALIGNDB|wc -l) -gt 0 ] ; then
     $bb echo "Already checked: $DIR/$APK"
    else
      $ZIP_APKS -c 4 $APK
      if [ $? -eq 0 ] ; then
        $bb echo "Already aligned: $DIR/$APK" | tee -a $LOG_FILE
        grep "$DIR/$APK" $ZIPALIGNDB > /dev/null || $bb echo $DIR/$APK >> $ZIPALIGNDB
      else
        $bb echo "Now aligning: $DIR/$APK"
        $ZIP_APKS -f 4 $APK /cache/$APK
        busybox mount -o rw,remount /system
        cp -f -p /cache/$APK $APK
        busybox rm -f /cache/$APK
        grep "$DIR/$APK" $ZIPALIGNDB > /dev/null || $bb echo $DIR/$APK >> $ZIPALIGNDB
      fi
    fi
  done
done

$bb mount -o ro,remount /system
touch $ZIPALIGNDB
$bb echo "Automatic ZipAlign finished at $( date +"%m-%d-%Y %H:%M:%S" )";
$bb echo "-------------------------------------------------------------";

exit
