#!/system/bin/sh
#
# Anarkia1976
# Enable Frandom
#

chmod 666 /dev/frandom

mv /dev/random /dev/random.ori
ln /dev/frandom /dev/random
chmod 666 /dev/random

mv /dev/urandom /dev/urandom.ori
ln /dev/frandom /dev/urandom
chmod 666 /dev/urandom
